name       : libgtksourceview
version    : 3.22.2
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gtksourceview/3.22/gtksourceview-3.22.2.tar.xz : 6ce84231dd0931cc747708434ca2f344c65a092dd6e1a800283fe0748773af5e
license    : GPL-2.0+
summary    : Syntax highlighting text editing C library
builddeps  :
    - pkgconfig(gtk+-3.0)
component  : desktop.gnome.core
description: |
    GtkSourceView is a portable C library that extends the standard GTK+ framework for multiline text editing with support for configurable syntax highlighting, unlimited undo/redo, UTF-8 compliant caseless searching, printing and other features typical of a source code editor.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
