name       : libgtksourceview4
version    : 4.8.3
release    : 27
source     :
    - https://download.gnome.org/sources/gtksourceview/4.8/gtksourceview-4.8.3.tar.xz : c30019506320ca2474d834cced1e2217ea533e00eb2a3f4eb7879007940ec682
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Syntax highlighting text editing C library
description: |
    GtkSourceView is a portable C library that extends the standard GTK+ framework for multiline text editing with support for configurable syntax highlighting, unlimited undo/redo, UTF-8 compliant caseless searching, printing and other features typical of a source code editor.
replaces   :
    - libgtksourceview
    - devel :
        - libgtksourceview-devel
    - dbginfo :
        - libgtksourceview-dbginfo
    - docs :
        - libgtksourceview-docs
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
    - valadoc
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
