name       : libgtksourceview
version    : 4.8.1
release    : 24
source     :
    - https://download.gnome.org/sources/gtksourceview/4.8/gtksourceview-4.8.1.tar.xz : d163d71b5fcafbc5b1eec6dd841edbdbcddd3a7511cd5fdcffd86b8bbfe69ac1
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Syntax highlighting text editing C library
description: |
    GtkSourceView is a portable C library that extends the standard GTK+ framework for multiline text editing with support for configurable syntax highlighting, unlimited undo/redo, UTF-8 compliant caseless searching, printing and other features typical of a source code editor.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
    - valadoc
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
