name       : libgtksourceview4
version    : 4.8.4
release    : 29
source     :
    - https://download.gnome.org/sources/gtksourceview/4.8/gtksourceview-4.8.4.tar.xz : 7ec9d18fb283d1f84a3a3eff3b7a72b09a10c9c006597b3fbabbb5958420a87d
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Syntax highlighting text editing C library
description: |
    GtkSourceView is a portable C library that extends the standard GTK+ framework for multiline text editing with support for configurable syntax highlighting, unlimited undo/redo, UTF-8 compliant caseless searching, printing and other features typical of a source code editor.
replaces   :
    - libgtksourceview
    - devel :
        - libgtksourceview-devel
    - dbginfo :
        - libgtksourceview-dbginfo
    - docs :
        - libgtksourceview-docs
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
    - valadoc
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
